export default {
    AUTH_LOGIN_ATTEMPT: 'AUTH_LOGIN_ATTEMPT',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

    AUTH_SIGN_UP_ATTEMPT: 'AUTH_SIGN_UP_ATTEMPT',
    AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
    AUTH_SIGN_UP_FAILURE: 'AUTH_SIGN_UP_FAILURE',
};
